
package rules;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class Message implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "status")
   private int status;

   public Message()
   {
   }

   public int getStatus()
   {
      return this.status;
   }

   public void setStatus(int status)
   {
      this.status = status;
   }

   public Message(int status)
   {
      this.status = status;
   }

}